# Generated by Django 5.2.4 on 2025-07-23 22:13

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('pwd', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('source', multiselectfield.db.fields.MultiSelectField(choices=[('videos', 'videos'), ('books', 'books'), ('comics', 'comics'), ('interction', 'interction'), ('chat', 'chat')], default='videos', max_length=65)),
                ('trigger_reason', multiselectfield.db.fields.MultiSelectField(choices=[('Digital visual', 'Digital visual'), ('social interaction', 'social interaction'), ('hadNotDoFromLastLong', 'hadNotDoFromLastLong')], default='Digital visual', max_length=65)),
                ('timesCount', models.IntegerField(default=1)),
                ('usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
