# Generated by Django 5.2.4 on 2025-09-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_schema',
            name='icon',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='Activity_icons/', width_field='width'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavrateactivity',
            unique_together={('usr_id', 'activity_id')},
        ),
    ]
