# Generated by Django 5.2.4 on 2025-09-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_activity_schema_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_schema',
            name='height',
        ),
        migrations.RemoveField(
            model_name='activity_schema',
            name='width',
        ),
        migrations.AlterField(
            model_name='activity_schema',
            name='icon',
            field=models.FileField(blank=True, default='Activity_icons/default_icon.svg', null=True, upload_to='Activity_icons/'),
        ),
    ]
