# Generated by Django 5.2.6 on 2025-09-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_activity_schema_height_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrecords',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='start_time_before_end_time'),
        ),
    ]
